src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuestionsRepository::class)]
class Questions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $question_text = null;

    #[ORM\Column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'formAnswer', targetEntity: Reponses::class)]
    private $reponses;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nomQuestion = null;

    public function __construct()
    {
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestionText(): ?string
    {
        return $this->question_text;
    }

    public function setQuestionText(?string $question_text): self
    {
        $this->question_text = $question_text;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Reponses>
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponses $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses->add($reponse);
            // $reponse->setformAnswer($this);
        }

        return $this;
    }

    public function removeReponse(Reponses $reponse): self
    {
        if ($this->reponses->removeElement($reponse)) {
            // set the owning side to null (unless already changed)
            // if ($reponse->getformAnswer() === $this) {
            //     $reponse->setformAnswer(null);
            // }
        }

        return $this;
    }

    public function getNomQuestion(): ?string
    {
        return $this->nomQuestion;
    }

    public function setNomQuestion(?string $nomQuestion): self
    {
        $this->nomQuestion = $nomQuestion;

        return $this;
    }

}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Serializer\Annotation\Ignore;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;
use Serializable;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[Vich\Uploadable]
#[UniqueEntity(fields: ['email'], message: 'Il y a déjà un compte avec cet email !')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface, Serializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column (type: "json")]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 125, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 200, nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $file = null;

    #[Vich\UploadableField(mapping: 'featured_profils', fileNameProperty: 'file')]  
    #[Assert\File(maxSize:'2M', maxSizeMessage:  'La taille du fichier ne doit pas dépasser 2 Mo.')]
    private $imageFile;

    #[ORM\Column(type: 'boolean')]
    private $is_verified = false;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private ?string $resetToken;

    #[ORM\Column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Reponses::class, orphanRemoval: true)]
    private Collection $reponses;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Subscription::class)]
    private Collection $subscriptions;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $stripeId = null;

    public function __construct()
    {
        $this->reponses = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->subscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(?string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getImageFile(File $image = null)
    {
        return $this->imageFile;
    }

    public function setImageFile(File $image = null)
    {        
        $this->imageFile = $image;

         if($image) {
            $this->file = $image->getFilename();
             $this->updated_at = new \DateTime('now');
         }

    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(?bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Reponses>
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponses $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses->add($reponse);
            $reponse->setUser($this);
        }

        return $this;
    }

    public function removeReponse(Reponses $reponse): self
    {
        if ($this->reponses->removeElement($reponse)) {
            // set the owning side to null (unless already changed)
            if ($reponse->getUser() === $this) {
                $reponse->setUser(null);
            }
        }

        return $this;
    }
    
     /**
     * @return Collection<int, Subscription>
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions->add($subscription);
            $subscription->setUser($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscription): self
    {
        if ($this->subscriptions->removeElement($subscription)) {
            // set the owning side to null (unless already changed)
            if ($subscription->getUser() === $this) {
                $subscription->setUser(null);
            }
        }

        return $this;
    }

    public function hasActiveSubscription(): bool
    {
        foreach ($this->subscriptions as $subscription) {
            if ($subscription->isActive()) {
                return true; // L'utilisateur a au moins un abonnement actif
            }
        }

        return false; // Aucun abonnement actif trouvé
    }

    public function getStripeId(): ?string
    {
        return $this->stripeId;
    }

    public function setStripeId(?string $stripeId): self
    {
        $this->stripeId = $stripeId;

        return $this;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->file,
            // see section on salt below

templates/userAccount/mesVoyages.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage + | Mes voyages {% endblock %}

{% block body %}
<h1>🚀 Liste de tes voyages de rêve {{user.prenom}} 🚀</h1>
{% if mesVoyages is empty %}
<p>Vous n'avez pas encore soumis de formulaires de voyage.</p>
{% else %}

    {% for formNumber, responses in responsesByForm %}
    <article id="article">
        <h2>Numéro de formulaire : {{ formNumber }}</h2>
        <p>
            <ul>
                {% for response in responses %}
                    <li>
                        <span>Question : {{ response.question.questionText }}</span>
                        <p>Réponse : {{ response.laReponse }}</p>
                    </li>
                {% endfor %}

                {% for response in responses %}
                    {% if loop.first %}
                        <hgroup>
                            <h3>Planning de l'IA</h3>
                            <p>{{ response.reponseIA|raw|nl2br }}</p>
                        </hgroup>
                    {% endif %}
                {% endfor %}
            </ul>
        </p>
        {% for response in responses %}
            {% if loop.first %}
        <footer>
            <small><em>Formulaire soumis le {{ response.createdAt.format('d m Y à H:i') }}</em></small>
        </footer>
            {% endif %}
        {% endfor %}
      </article>

    {% endfor %}

{% endif %}
{% endblock %}

templates/userAccount/modification_profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage + | Mon Compte {% endblock %}

{% block body %}

{{ form_start(userForm) }}
{{ form_end(userForm) }}
<button class="outline"><a href="{{path('myAccount')}}">Retour</a></buttton>

{% endblock %}

templates/userAccount/myAccount.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voyage + | Mon Compte {% endblock %}

{% block body %}

<div class="container">
    <div class="container_informations">
        <div class="content_informations">
            <hgroup class="infos">
                {% if connectedUser.file != null %}
                <img src="{{vich_uploader_asset(connectedUser, 'imageFile')}}" class="userAvatar" alt="user avatar">
                {% else %}
                <img src="{{asset('images/defaultUser/user.jpg')}}" class="userAvatar" alt="default avatar">
                {% endif %}
                <h3>{{connectedUser.prenom}} {{connectedUser.nom}}</h3> 
                <p>{{connectedUser.description}}</p>
                <p><i class="fa fa-map-marker"></i> {{connectedUser.ville}}, {{connectedUser.codePostal}}</p>
            </hgroup>
        </div>
        <div class="grid">
            <button><a href="{{path('app_generate_plan')}}">Planifier mon prochain séjour</a></buttton>
            <button class="outline"><a href="{{path('app_contact')}}">Nous contactez</a></buttton>
            <button><a href="{{path('modif_profil')}}">Modifier mon profil</a></buttton>
        </div>
        <hgroup class="containerUserInfo">
            <div class="grid">
                <div>
                    <article id="article">
                        {% if distinctFormNumbers > 1 %}
                        <h4>Nombre de planning générés</h4>
                        {% else %}
                        <h4>Nombre de planning généré</h4>
                        {% endif %}
                            <p class="planningNumber">{{distinctFormNumbers}}</p>
                        <footer><small>Par Voyageur+</small></footer>
                    </article>
                </div>
                <div>
                    <article id="article">
                        <h4>Un abonnement en cours ?</h4>
                        {#
                            Correction: on ne tente plus de parser une chaîne FR du type "03/09/2024 à 19:21" via le filtre date() (erreur strtotime).
                            Attendu côté contrôleur (idéal) :
                              - variables bool : subscriptionActive, subscriptionExpired
                              - OU un objet DateTime : endDateObj (et éventuellement startDateObj)
                              - OU un timestamp numérique : endDateTimestamp
                            Ce bloc crée des fallbacks sans jamais parser la chaîne formatée.
                        #}
                        {% set nowTs = "now"|date('U') %}
                        {# Récupération sécurisée du timestamp de fin #}
                        {% set endTs =
                            endDateObj is defined
                                ? endDateObj|date('U')
                                : (endDateTimestamp is defined
                                    ? endDateTimestamp
                                    : null)
                        %}
                        {# Flags avec fallback si non fournis par le contrôleur #}
                        {% set subscriptionActiveFlag = subscriptionActive is defined ? subscriptionActive : (hasActiveSubscription and endTs is not null and endTs >= nowTs) %}
                        {% set subscriptionExpiredFlag = subscriptionExpired is defined ? subscriptionExpired : (hasActiveSubscription and endTs is not null and endTs < nowTs) %}

                        {% if hasActiveSubscription and subscriptionActiveFlag %}
                            <p>
                                Vous avez souscris à un abonnement <strong>{{ planName }}</strong>. <br><br>
                                Votre abonnement s'étend du <br> <strong>{{ startDate }}</strong> <br> au <br> <strong>{{ endDate }}</strong>.
                            </p>
                        {% elseif hasActiveSubscription and subscriptionExpiredFlag %}
                            <p>
                                Votre abonnement <strong>{{ planName }}</strong> a expiré le <strong>{{ endDate }}</strong>. <br>
                                Renouvelez pour continuer à générer des plannings sans limitation.
                            </p>
                        {% else %}
                            <p>
                                Vous n'avez aucun abonnement en cours !
                            </p>
                        {% endif %}
                        <footer><small>Par Voyageur+</small></footer>
                    </article>
                </div>
                <div>
                    <article id="article">
                        <h4>Abonné à la newsletter ?</h4>
                        {% if isOnNewsletterSubscriber == true %}
                            <p>
                                Magnifique. Vérifiez vos mails, des jeux concours, des cadeaux et de nombreuses actualités vous attendent. 💫
                            </p>
                            {% else %}
                            <p>
                                Vous n'êtes pas encore abonné à la Newsletter, vous ratez un nombre incalculable de promotions et d'actualité en tout genre. Dommage 😔
                            </p>
                            {% endif %}
                        <footer><small>Par Voyageur+</small></footer>
                    </article>
                </div>
            </div>
        </hgroup>
        
    </div>
</div>

{% endblock %}